### ISSUE TITLE
Zero?

### ISSUE THREAD

**Issue by anubisthejackle** [hgoebl/doublemetaphone#3]
When passing the name Mokshith, I get this as my output:

{ primary: 'MKX0', alternate: 'MKXT' }

The last character in Primary is a zero. I'm just wanting to verify that this is an accurate result, as I'm not sure what the number 0 has to do with metaphone?

**Comment by hgoebl** [comment]
Thanks for giving feedback!

Most probably the zero should mean the "th".
At least the [Apache Jakarta Commons Java implementation](http://grepcode.com/file/repo1.maven.org/maven2/commons-codec/commons-codec/1.3/org/apache/commons/codec/language/DoubleMetaphone.java#713) produces a 0 as well.

**Comment by anubisthejackle** [comment]
Yea, after doing some googling on it, I realized it has to do with emphasis.
